---
- hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
    - vpro_stack_vars/cloudvars
  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: devops-hari
         group: ansible-sg
         region: "{{region}}"
         instance_type: t2.micro
         image: ami-00ddb0e5626798373
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2_info

    - debug:
        msg: "{{ec2_info}}"
