- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven

    - name: clone source code from github
      git:
        repo: 'https://github.com/Harinath120/vprofile-project.git'
        dest: ./vprofile-repo
        version: vp-rem
      register: git_status


    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: vprofile-repo
      when: git_status.changed
      register: mvn_info
#    - debug:
#        msg: "{{mvn_info}}"

    - name: copy artifacts to files directory
      command: "cp /ansible-practice/stack_play/vprofile-repo/target/vprofile-v2.war files/"

    - name: copy SQL file to files directory
      command: "cp /ansible-practice/stack_play/vprofile-repo/src/main/resources/db_backup.sql files/"


