- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install jdk, maven, git
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - java-1.8.0-openjdk
        - maven

    - name: clone source code from github
      git:
        repo: 'https://github.com/Harinath120/vprofile-project.git'
        dest: ./vprofile-repo
        version: vp-rm
      register: git_status


    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: vprofile-repo
      when: git_status.changed
      register: mvn_info
#    - debug:
#        msg: "{{mvn_info}}"

    - name: copy artifacts to files directory
      command: "cp Vprofile-repo/target/vprofile-v3.war files/"

    - name: copy SQL file to files directory
      command: "cp Vprofile-repo/src/main/resources/db_backup.sql files/"


