---
- name: setup Mysql with accounts db and remote login
  hosts: dbsrvgrp
  tasks:
    - name: Installing Mysql service and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - libmysqlclient-dev
        

    - name: start and enable mysql service
      service: 
         name: mysql
         state: started
         enabled: yes

    