---
- name: deploy SQL file on accounts db
  hosts: dbsrvgrp
  tasks:
    - name: Copy SQL to dbsrv 
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      
    - name: Restoring DB
      mysql_db:
        name: accounts
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
