--- 
- name: Install & setup Rabbitmq with user 
  hosts: rmqsrvgrp
  tasks:
    - name: Install Erlang Repository package
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

    - name: add an Erlang solution public key
      apt-key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: Install Erlang
      apt:
        name: erlang 
        update_cache: yes
        state: present 

    - apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq/debian xenial main
        state: present 


    - apt-key:
        url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
        state: present 

    - name: Add an apt signing key, uses whichever key is at the url 
      apt-key:
        url: https://dl.bintray.com/rabbitmq/keys/rabbitmq-release-signing-key.asc
        state: Present 

    - name: Install Rabbit MQ 
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: start & Enable rabbitmq 
      service:
        name: rabbitmq-server
        state: started 
        enabled: yes

    - name: config setup 
      copy: 
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ 

    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .* 
        write_priv: .* 
        tags: administrator
        state: present 
      notify:
        - Restart RMQ 

    - name: Eanbles the rabbitmq_management plugin 
      rabbitmq_plugin: 
        names: rabbitmq_management
        state: enabled 
      notify: 
        - Restart RMQ 

  handlers:
    - name: Restart RMQ 
      service:
        name: rabbitmq-server
        state: restarted