- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.22.190 web01
          172.31.30.199 web02
          172.31.38.56 app01
          172.31.40.159 app02
          172.31.24.150 rmq01
          172.31.19.187 mc01
          172.31.24.66 db01