- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.30.225 web01
          172.31.18.55 web02
          172.31.37.67 app01
          172.31.36.209 app02
          172.31.31.186 rmq01
          172.31.21.127 mc01
          172.31.19.61 db01