- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.28.164 web01
          172.31.36.105 web02
          172.31.23.78 app01
          172.31.43.231 app02
          172.31.20.168 rmq01
          172.31.20.19 mc01
          172.31.26.195 db01