- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.24.109 web01
          172.31.43.188 web02
          172.31.23.190 app01
          172.31.37.33 app02
          172.31.24.105 rmq01
          172.31.24.246 mc01
          172.31.29.91 db01