- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.18.38 web01
          172.31.17.246 web02
          172.31.34.71 app01
          172.31.47.253 app02
          172.31.26.236 rmq01
          172.31.22.148 mc01
          172.31.26.142 db01