- name: set host ip to mapping in /etc/hosts file of the all instances in the stack
  hosts: all
  tasks:
    - name: Update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          172.31.22.89 web01
          172.31.46.231 web02
          172.31.23.38 app01
          172.31.43.197 app02
          172.31.30.96 rmq01
          172.31.30.217 mc01
          172.31.16.129 db01